version: "2"
services:
  aws-local: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567-4583:4567-4583"
    environment:
      - SERVICES=ssm
      - DEBUG=
      - DATA_DIR=
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ".tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"